description: 'Summarize eval'

prompts:
  - 'summarize'

providers:
  - id: ./src/promptfoo-api-provider.mjs
    label: gpt4
    config:
      model: gpt-4
  - id: ./src/promptfoo-api-provider.mjs
    label: gpt3.5
    config:
      model: gpt-3.5-turbo

defaultTest:
  options:
    provider:
      id: azureopenai:chat:gpt-4
      config:
        apiHost: 'tnrllmproxy.azurewebsites.net'
  assert:
    - type: llm-rubric
      value: mentions Markdown
    - type: factuality
      value: Markdown is a text-based syntax to describe documents.
tests:
  - vars:
      spec: src/rag/markdown.md
  - vars:
      spec: src/rag/Document.docx
