name: build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: typecheck
              run: yarn typecheck
            - name: compile
              run: yarn compile
            - name: run cli
              run: node packages/cli/built/gptools.js run code-xray packages/sample/src/counting.gpspec.md -d -ot $GITHUB_STEP_SUMMARY
            - name: run cli pipe
              run: cat packages/sample/src/counting.gpspec.md | node packages/cli/built/gptools.js run code-xray -d -ot $GITHUB_STEP_SUMMARY
            - name: run cli glob
              run: node packages/cli/built/gptools.js run code-xray packages/sample/src/counting.py packages/sample/src/*.ts -d -o .gptools/tmp/cli -ot $GITHUB_STEP_SUMMARY
            - name: package vscode
              run: yarn package
