name: build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: typecheck
              run: yarn typecheck
            - name: compile
              run: yarn compile
            - name: compile tests
              run: yarn test:compile
            - name: core tests
              run: yarn test:core
            - name: unit tests
              run: yarn test:samples
            - name: install sharp
              run: cd docs && yarn add sharp@0.32.6
            - name: docs
              run: yarn build:docs
            - name: run cli
              run: node packages/cli/built/genaiscript.cjs run code-xray packages/sample/src/counting.gpspec.md --prompt -ot $GITHUB_STEP_SUMMARY -l single
            - name: run cli pipe
              run: cat packages/sample/src/counting.gpspec.md | node packages/cli/built/genaiscript.cjs run code-xray --prompt -ot $GITHUB_STEP_SUMMARY -l multi
            - name: run cli glob
              run: node packages/cli/built/genaiscript.cjs run code-xray packages/sample/src/counting.py packages/sample/src/*.ts --prompt -o .genaiscript/tmp/cli -ot $GITHUB_STEP_SUMMARY -l glob
            - name: package vscode
              run: yarn package

