name: genai-frontmatter
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: compile
              run: yarn compile
            - name: front matter
              run: yarn genai:frontmatter
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            - name: install sharp
              run: cd docs && yarn add -D sharp
            - name: docs
              run: yarn build:docs
            - name: Commit AI frontmatters
              if: success() || failure()
              run: |
                  git config pull.ff only
                  git pull
                  git add docs/src/**/*.md
                  git add docs/src/**/*.mdx
                  git commit -m "[genai] frontmatter updates" || echo "No changes to commit"
                  git push
