name: nightly test

on:
    workflow_dispatch:
    schedule:
        - cron: "0 7 * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
            OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            AZURE_OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            AZURE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            PROMPTFOO_CACHE_PATH: .genaiscript/cache/promptfoo
            PROMPTFOO_CONFIG_DIR: .genaiscript/cache
            PROMPTFOO_DISABLE_TELEMETRY: 1
            PROMPTFOO_DISABLE_UPDATE: 1
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: typecheck
              run: yarn typecheck
            - name: compile
              run: yarn compile
            - name: run test within scripts
              run: yarn test:scripts
