name: ollama smoke tests
on:
    workflow_dispatch:
    push:
        paths:
            - yarn.lock
            - "packages/core/**/*"
            - "packages/cli/**/*"
            - "packages/samples/**/*"

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: typecheck
              run: yarn typecheck
            - name: compile
              run: yarn compile
            - name: download ollama docker
              run: docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
            - name: run summarize-ollama-phi3
              run: yarn test:summarize --model ollama:phi3 --out ./temp
            - name: Add comment to PR
              uses: actions/github-script@v5
              if: github.event_name == 'pull_request'
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const fs = require('fs/promises');
                      const comment = await fs.readFile('./temp/res.output.md', 'utf8');
                      await github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: comment
                      })
