name: pr phi3 summary test
on:
    workflow_dispatch:
    pull_request_review:
        types: [submitted]
jobs:
    approved:
        if: github.event.review.state == 'APPROVED'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: typecheck
              run: yarn typecheck
            - name: compile
              run: yarn compile
            - name: download ollama docker
              run: docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
            - name: run summarize-ollama-phi3
              run: yarn test:scripts summarize-ollama-phi3
